version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: instabug_chat_system_development
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        links:
            - elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        hostname: elasticsearch
        ports:
            - "9200:9200"
    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: instabug_chat_system_development
            DB_PASSWORD: password
            DB_HOST: db
            ELASTICSEARCH_URL: http://elasticsearch:9200